apiVersion: v1
kind: Secret
metadata:
  name: nexusforge-redis-secret
  namespace: nexusforge
type: Opaque
data:
  # change this value (base64 encoded) before deploying to prod
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==
